base_url = "http://localhost:11434"
model_name = ""qwen2.5:7b""
chat_endpoint = "/api/chat/"
batch_endpoint = "/api/chat"
max_tokens = 512
allowed_timeout = 60
temperature = 0.0
top_p = 1.0
seed = 42
